FROM golang:1.8 as builder
USER 10001
WORKDIR /go/src/app
COPY . ./
RUN go install
RUN ldd /go/bin/app | grep -q "not a dynamic executable"

FROM scratch
USER 10001
EXPOSE 8080
COPY --from=builder /go/bin/app /app
CMD ["/app"]
